### ISSUE TITLE
Adc~

### ISSUE THREAD

**Issue by dennisdebel** [jlswbs/ESP32_PureData#1]
Wow! I got your patches to work on my esp32 (a1s), great job! One thing that causes the esp32 to crash is when I try an audio passthrough (adc~ to dac~ in pd). Have you tried using the adc~ / audio input?

**Comment by jlswbs** [comment]
I haven't tried the ADC yet, but I'm going to do it, the next step will be controlling the PD parameter

**Comment by dennisdebel** [comment]
Using adc~ as only object in a patch seems fine... the chip is not crashing. I will look a bit more into this issue. Btw I am using the Es8388V1 variant of the ESP32 A1S. 

Edit: the error I am getting is: assert failed: void audio_tools::PureDataStream::readWrite(int) PureDataStream.h:109 (eff == sample_size)

**Comment by dennisdebel** [comment]
This might be my issue:

“I recommend to make sure that the input format and output format is
consistent, otherwise you need to change the format in PD”[0]

[0]
https://pschatzmann.github.io/arduino-audio-tools/classaudio__tools_1_1_pure_data_stream.html#details

I havent managed yet though.

**Comment by dennisdebel** [comment]
There is actually a "streams-generator-pd-audiokit.ino" pd adc to dac example in the arduino-audio-tools library by the aforementioned p.schatzmann. It compiles and runs, but I do not understand how it works (he is simulating the adc with a sinewave in the patch?). This could be an interesting starting point.

**Comment by dennisdebel** [comment]
@xi-bot, well done, thank you for positing. It works on my AudioKitEs8388V1 board here (although there is the mic/aux selection issue...[0]). What was your process of figuring this out if I may ask?

[0] [Phil Schatzmann](https://www.pschatzmann.ch/home/) seems to have a discussion on his website regarding this issue. It seems a few capacitors have to be (re)moved, see [here](https://www.pschatzmann.ch/home/2021/12/15/the-ai-thinker-audiokit-audio-input-bug/)
